<td>{{ $entity->model_weight }}</td>
<td>{{ $entity->locomotive->sound }}</td>
<td>{{ $entity->locomotive->decoder_type }}</td>
<td>{{ $entity->railway_management }}</td>
<td>{{ $entity->epoch }}</td>
<td>{{ $entity->locomotive->name }}</td>
<td>{{ $entity->locomotive->axle_load }}</td>
<td>{{ $entity->total_length }}</td>
<td>{{ $entity->locomotive->wheel_base }}</td>
<td>{{ $entity->locomotive->service_weight }}</td>
<td>{{ $entity->maximum_speed }}</td>
<td>{{ $entity->locomotive->type_of_heating }}</td>
<td>{{ $entity->locomotive->axle_arrangement }}</td>
<td>{{ $entity->locomotive->power }}</td>
<td>{{ $entity->usage_notes }}</td>
<td>{{ $entity->locomotive->address_ddc }}</td>
<td>{{ $entity->locomotive->type_ddc }}</td>
<td>{{ $entity->locomotive->speed_steps }}</td>
<td>{{ $entity->locomotive->mode }}</td>
<td>{{ $entity->locomotive->analog }}</td>
